collections:
  projects:
    output: true

permalink: /:categories/:title

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  - scope:
      path: ""
    values:
      layout: "base"